version: '3.8'
services: 
  traffic-counter:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
        SQLUSER: root
        SQLPASSWD: secret
        SQLDATABASE: mikrotik
        SQLHOST: database
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 8090:80
    environment:
        SQLUSER: root
        SQLPASSWD: secret
        SQLDATABASE: mikrotik
        SQLHOST: database
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    ports:
        - "3306:3306"
    volumes:
        - ./mikrotik.sql:/docker-entrypoint-initdb.d/mikrotik.sql
        - /home/pp/db-mikrotik/:/var/lib/mysql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: mikrotik
        MYSQL_USER: mikrotik
        MYSQL_PASSWORD: secret  
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 20s
      timeout: 3s
      retries: 10
